language: php
services:
  - mongodb
php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    # Install MongoDB driver
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    # Install dev requirements
    - composer install 
